# Generated by Django 3.2 on 2021-05-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20210517_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='fileName',
        ),
    ]
