# Generated by Django 3.2 on 2021-06-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_remove_card_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='fileName',
            field=models.CharField(default='', max_length=25),
        ),
    ]
